name: "Tests"
on: [push, pull_request]
jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run unit test
        run: bash resources/test.sh 2>&1